=begin
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
=end

fibset = [1, 2]
(3...4000000).each do |n|
  a = fibset[fibset.length - 1]
  b = fibset[fibset.length - 2]
  p "----------"
  p "a: #{a}"
  p "b: #{b}"
  p "n: #{n}"
  p "----------"
  if (n == a + b) then 
    fibset << n
  end
end

sum = 0
fibset.each do |f|
  if f.even? then 
    sum = sum + f
  end
end
p sum
